package com.example.recall_ai.di

import com.example.recall_ai.BuildConfig
import com.example.recall_ai.data.remote.api.WhisperApiService
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import com.example.recall_ai.config.AiModelConfig
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit
import javax.inject.Named
import javax.inject.Singleton

/**
 * Provides all HTTP infrastructure: OkHttp, Retrofit, Gson, and the Whisper
 * Retrofit service interface. Everything in this module is @Singleton so a
 * single connection pool is shared across every network call in the app.
 *
 * ── Preconditions (must be satisfied before this module compiles) ─────────
 *
 * 1. app/build.gradle.kts must contain inside android { buildFeatures { } }:
 *        buildConfig = true
 *    Without this, AGP 8+ does not generate the BuildConfig class at all, and
 *    every BuildConfig.* reference is an "unresolved reference" compile error.
 *
 * 2. app/build.gradle.kts must contain inside android { defaultConfig { } }:
 *        buildConfigField("String", "OPENAI_API_KEY",
 *            "\"${localProperties["OPENAI_API_KEY"] ?: ""}\"")
 *        buildConfigField("String", "GEMINI_API_KEY",
 *            "\"${localProperties["GEMINI_API_KEY"] ?: ""}\"")
 *    Without these, BuildConfig.OPENAI_API_KEY and BuildConfig.GEMINI_API_KEY
 *    do not exist and the two @Named provider methods below will not compile.
 *
 * 3. local.properties (project root, git-ignored) must contain:
 *        OPENAI_API_KEY=sk-proj-...
 *        GEMINI_API_KEY=AIzaSy-...
 *    The build.gradle.kts reads this file and stamps the values into BuildConfig
 *    at compile time. Missing keys produce an empty string "", not a crash —
 *    the app compiles but all API calls return 401 Unauthorized at runtime.
 *
 * ── Responsibility boundary ───────────────────────────────────────────────
 * This module owns HTTP infrastructure only: the client, serialiser, Retrofit
 * instance, and raw API keys. It does NOT choose which TranscriptionService or
 * SummaryService implementation is active — that is RepositoryModule's job.
 *
 * GeminiStreamingClient is intentionally absent from this module.
 * It is annotated with @Singleton and @Inject constructor, so Hilt constructs
 * it automatically using OkHttpClient, Gson, and "gemini_api_key" from this
 * module. Adding a @Provides method for it here would create a duplicate
 * binding and fail at compile time with a Dagger error.
 *
 * ── Timeout values ────────────────────────────────────────────────────────
 *   connect  15 s   TCP handshake — fails fast when server is unreachable
 *   write    60 s   WAV upload — 960 KB on a slow mobile connection
 *   read     60 s   Whisper inference response wait
 *   call    120 s   Hard ceiling for the full request lifecycle
 *
 * ── Log level ─────────────────────────────────────────────────────────────
 * DEBUG builds → HEADERS only (never BODY — that would dump the entire WAV
 * as base64, producing megabytes of logcat noise per transcription request).
 * RELEASE builds → NONE.
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    private val WHISPER_BASE_URL = AiModelConfig.WHISPER_BASE_URL

    // ── Serialisation ─────────────────────────────────────────────────────

    @Provides
    @Singleton
    fun provideGson(): Gson = GsonBuilder()
        .setLenient()
        .create()

    // ── HTTP client ───────────────────────────────────────────────────────

    @Provides
    @Singleton
    fun provideOkHttpClient(): OkHttpClient {
        // BuildConfig.DEBUG is a Boolean generated by AGP.
        // It resolves correctly ONLY when buildConfig = true is set in
        // app/build.gradle.kts → android → buildFeatures.
        val logLevel = if (BuildConfig.DEBUG) {
            HttpLoggingInterceptor.Level.HEADERS
        } else {
            HttpLoggingInterceptor.Level.NONE
        }
        val logging = HttpLoggingInterceptor().apply { level = logLevel }

        return OkHttpClient.Builder()
            .connectTimeout(15,  TimeUnit.SECONDS)
            .writeTimeout(60,    TimeUnit.SECONDS)
            .readTimeout(0,     TimeUnit.SECONDS)
            .callTimeout(0,    TimeUnit.SECONDS)
            .addInterceptor(logging)
            .build()
    }

    // ── Retrofit ─────────────────────────────────────────────────────────

    @Provides
    @Singleton
    fun provideRetrofit(client: OkHttpClient, gson: Gson): Retrofit =
        Retrofit.Builder()
            .baseUrl(WHISPER_BASE_URL)
            .client(client)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()

    @Provides
    @Singleton
    fun provideWhisperApiService(retrofit: Retrofit): WhisperApiService =
        retrofit.create(WhisperApiService::class.java)

    // ── API keys ──────────────────────────────────────────────────────────
    //
    // Injected as @Named Strings so individual service classes receive only
    // the key they need, without importing BuildConfig themselves.
    //
    // BuildConfig.OPENAI_API_KEY and BuildConfig.GEMINI_API_KEY are custom
    // fields that only exist if buildConfigField(...) entries are present in
    // app/build.gradle.kts defaultConfig { }. See the class KDoc above for
    // the exact lines required.
    //
    // @Named String providers deliberately omit @Singleton — String is a
    // value type and constructing it on each injection is zero-cost. Adding
    // @Singleton to a String @Provides can cause Dagger scoping warnings.

    @Provides
    @Named("openai_api_key")
    fun provideOpenAiApiKey(): String = ""

    @Provides
    @Named("gemini_api_key")
    fun provideGeminiApiKey(): String = BuildConfig.GEMINI_API_KEY
}